[[git_users]]
label = "Work"
name = "Taro Yamada"
email = "taro.yamada@company.example"
default = true
default_repositories = [
  "example-repo",
  "another",
]

[[git_users]]
label = "Personal"
name = "Taro Yamada"
email = "taro.yamada@example.mail.com"
default = false
default_repositories = ["personal-repo"]

[[git_users]]
label = "Customer (Contract)"
name = "Taro Yamada"
email = "taro.yamada@customer.example"
default = false
default_repositories = ["project"]
